import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Search, Loader2, Package } from "lucide-react";
import SafeImage from "@/components/SafeImage";

const AdminProducts = () => {
  const [products, setProducts] = useState<any[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => { loadProducts(); }, []);

  const loadProducts = async () => {
    setLoading(true);
    const { data } = await supabase.from("products").select("*, product_categories(name)").order("created_at", { ascending: false }).limit(100);
    setProducts(data || []);
    setLoading(false);
  };

  const filtered = products.filter(p =>
    !search || p.name?.toLowerCase().includes(search.toLowerCase()) || p.brand?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-lg font-display text-foreground/80">Products</h1>
        <span className="text-[11px] text-foreground/75">{products.length} total</span>
      </div>

      <div className="flex items-center gap-2 rounded-lg border border-border/20 bg-card/30 px-3 py-2">
        <Search className="h-4 w-4 text-foreground/70" />
        <input
          value={search}
          onChange={e => setSearch(e.target.value)}
          placeholder="Search products…"
          className="flex-1 bg-transparent text-[13px] text-foreground outline-none placeholder:text-foreground/50"
        />
      </div>

      {loading ? (
        <div className="flex justify-center py-12"><Loader2 className="h-4 w-4 animate-spin text-foreground/75" /></div>
      ) : products.length === 0 ? (
        <div className="py-16 text-center space-y-3">
          <Package className="mx-auto h-8 w-8 text-foreground/70" />
          <p className="text-[13px] text-foreground/70">No products yet</p>
          <p className="text-[11px] text-foreground/70 max-w-xs mx-auto">Products generated by AI recommendations will appear here. You can also add products manually.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-3">
          {filtered.map(p => (
            <div key={p.id} className="flex gap-3 rounded-xl border border-border/20 bg-card/30 p-3">
              <SafeImage
                src={p.images?.[0]}
                alt={p.name}
                className="h-16 w-16 rounded-lg object-cover shrink-0"
                fallbackClassName="h-16 w-16 rounded-lg shrink-0"
              />
              <div className="min-w-0 flex-1 space-y-1">
                <p className="text-[12px] font-medium text-foreground/70 truncate">{p.name}</p>
                <p className="text-[10px] text-foreground/75">{p.brand || "—"} · {p.product_categories?.name || "Uncategorized"}</p>
                <div className="flex items-center gap-2">
                  {p.price && <span className="text-[11px] text-foreground/75">${p.price}</span>}
                  {p.is_featured && <span className="text-[11px] bg-accent/10 text-accent/70 px-1.5 py-0.5 rounded">Featured</span>}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default AdminProducts;
